### ISSUE TITLE
tslint preprocess not registered

### ISSUE THREAD

**Issue by thepian** [yisraelx/karma-tslint#1]
```
20 08 2018 19:26:00.733:ERROR [preprocess]: Can not load "tslint", it is not registered!
  Perhaps you are missing some plugin?
```

```
    preprocessors: {
        // 'shared/**/*.ts': ['tslint'],
        'sme/**/*.ts': ['karma-tslint'],
        // 'ent/**/*.ts': ['tslint'],
    },
```

I tried to add this following the README to what I think is a pretty standard Angular 6.1 project.

Isn't a preprocessor not resolved with a pre & postfix? Shouldn't this module be called `karma-tslint-preprocessor` ?

**Comment by thepian** [comment]
Found it. It must be registered as a plugin. Perhaps that can be made clear in the README.

**Comment by yisraelx** [comment]
You can see that it is not registered in the `README` of any plugin.
https://www.npmjs.com/search?q=keywords:karma-plugin
https://github.com/karma-runner

This is registered only in the `karma` documentation
https://karma-runner.github.io/2.0/config/plugins.html

But I'll add it to the `README`, maybe it will help to other people.
